### ISSUE TITLE
Jellyfin won't start after trying to add fanart

### ISSUE THREAD

**Issue by leaderdog** [jellyfin/jellyfin-web#1023]
Hi,

I had the fanart issue where it wouldn't update the plugin. I followed the instructions on here to delete it when Jellyfin wasn't running then reinstall it. It said changes to take effect on restart and now Jellyfin crashes and won't start.  I realized it wouldn't start because of the fanart via the logs.  I delete the files in plugins and then Jellyfin started no problem.  I tried to reinstall the fanart plugin 4.0 and once again it dies at start up.

This is in the log:

`[2020-04-04 08:38:09.162 -06:00] [INF] [1] Main: Jellyfin version: "10.5.0"
[2020-04-04 08:38:09.186 -06:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--service", "--datadir", "C:\ProgramData\Jellyfin\Server"]
[2020-04-04 08:38:09.196 -06:00] [INF] [1] Main: Operating system: "Windows"
[2020-04-04 08:38:09.198 -06:00] [INF] [1] Main: Architecture: X64
[2020-04-04 08:38:09.201 -06:00] [INF] [1] Main: 64-Bit Process: True
[2020-04-04 08:38:09.203 -06:00] [INF] [1] Main: User Interactive: True
[2020-04-04 08:38:09.204 -06:00] [INF] [1] Main: Processor count: 8
[2020-04-04 08:38:09.206 -06:00] [INF] [1] Main: Program data path: "C:\ProgramData\Jellyfin\Server"
[2020-04-04 08:38:09.208 -06:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2020-04-04 08:38:09.209 -06:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2020-04-04 08:38:09.542 -06:00] [INF] [1] ServerConfigurationManager: Setting cache path: "C:\ProgramData\Jellyfin\Server\cache"
[2020-04-04 08:38:09.581 -06:00] [INF] [1] App: Loading assemblies
[2020-04-04 08:38:09.600 -06:00] [INF] [1] App: Loaded assembly "Jellyfin.Plugin.Fanart, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\Fanart\Jellyfin.Plugin.Fanart.dll"
[2020-04-04 08:38:09.604 -06:00] [FTL] [1] Main: Error while starting server.
System.IO.FileNotFoundException: Could not load file or assembly 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MediaBrowser.Common, Version=10.5.2.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Emby.Server.Implementations.ApplicationHost.DiscoverTypes()
   at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)

[2020-04-04 08:38:09.629 -06:00] [INF] [1] App: Disposing "CoreAppHost"
[2020-04-04 08:38:09.632 -06:00] [FTL] [1] Main: Unhandled Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.ApplicationHost.Dispose(Boolean dispose)
   at Emby.Server.Implementations.ApplicationHost.Dispose()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)`

forgot to add:
In dashboard it says:

`Fanart was installed
4/4/2020, 8:30:44 am
Version 4.0.0.0`

but it's not obviously because I deleted the plugin manually for it to even start.

so for now I've given up trying to install it :)

Windows 10 (1909) x64
Jellyfin version: 10.5.0

**Comment by MrTimscampi** [comment]
Hi, thanks for reporting the issue!

This issue is known and was already fixed in the nightly and should be released as part of 10.5.3.

Please see here for the PR implementing the fix: https://github.com/jellyfin/jellyfin/pull/2730
