### ISSUE TITLE
Restarting from the dashboard button results in UnhandledException

### ISSUE THREAD

**Issue by aferpa94** [jellyfin/jellyfin-web#108]
As the title say, when clicking the restart button, the process fails:
- Ubuntu 18.04, freshly installed Jellyfin.

[server.txt](https://github.com/jellyfin/jellyfin/files/2695880/server.txt)
[unhandled_5c9ffb66-5db6-4a8c-bae5-e85565bfce7b.txt](https://github.com/jellyfin/jellyfin/files/2695881/unhandled_5c9ffb66-5db6-4a8c-bae5-e85565bfce7b.txt)

**Comment by sparky8251** [comment]
Is this still a problem? I recall @Bond-009 or somesuch fixing the handling of shutdown around signals.

**Comment by dkanada** [comment]
We have been tracking this in jellyfin/jellyfin#1320 and there is a possible fix in the master branch, feel free to comment in the main issue if you are still having problems.

**Comment by jfranki** [comment]
Could we reopen this? When I try to restart the server from the dashboard I'm getting this:

> System.PlatformNotSupportedException: The server is unable to self-restart. Please restart manually.
   at Emby.Server.Implementations.ApplicationHost.Restart()
   at Emby.Server.Implementations.Services.ServiceExecGeneral.<>c__DisplayClass5_0.<CreateExecFn>b__0(Object service, Object request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

There is no feedback in the UI of the error either. The reason I would want to restart is the installation of an official plugin that apparently needs restarting the server for it to start working:

> [2020-09-23 11:42:25.605 +00:00] [INF] [56] Emby.Server.Implementations.Updates.InstallationManager: New plugin installed: "Playback Reporting" "7.0.0.0"
[2020-09-23 11:42:26.145 +00:00] [INF] [56] Emby.Server.Implementations.ApplicationHost: App needs to be restarted.
