### ISSUE TITLE
[10.6 NIGHTLY] List View endlessly loading

### ISSUE THREAD

**Issue by ferferga** [jellyfin/jellyfin-web#1431]
List view (and pages that have lists) that contains items without images will be endlessly loading.

Fixed in #1430

**Comment by dmitrylyzo** [comment]
I got this error in server log when loading `Playlists` page and Error 400 in response.
```
[2020-06-20 11:24:30.354 +03:00] [ERR] Error processing request. URL: "http://IP/jellyfin/Users/19049592d87b4ea7a149a747070f233d/Items?Fields=PrimaryImageAspectRatio%2CSortName%2CPath%2CPrimaryImageAspectRatio&ImageTypeLimit=1&ParentId=c00310d49d01f5352278e06b1b96160a&SortBy=IsFolder%2CSortName&SortOrder=Ascending"
System.ArgumentNullException: Value cannot be null. (Parameter 'factory')
   at Microsoft.Extensions.Logging.LoggerFactoryExtensions.CreateLogger[T](ILoggerFactory factory)
   at MediaBrowser.Controller.Entities.UserView.GetItemsInternal(InternalItemsQuery query)
   at MediaBrowser.Controller.Entities.Folder.GetItems(InternalItemsQuery query)
   at MediaBrowser.Api.UserLibrary.ItemsService.GetQueryResult(GetItems request, DtoOptions dtoOptions, User user)
   at MediaBrowser.Api.UserLibrary.ItemsService.GetItems(GetItems request)
   at MediaBrowser.Api.UserLibrary.ItemsService.Get(GetItems request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```
Server: nightly-20200620
Client: web bef977062e7cde96716efa23a98d06c4285e8f28

**Comment by ferferga** [comment]
@dmitrylyzo Hmm, so it seems we have two bugs related to list view. I haven't seen that one.

**Comment by dmitrylyzo** [comment]
What I have is from `Playlists` on the home screen.
I dig and found out that web doesn't provide `IncludeItemTypes`, or server should handle it somehow.
https://github.com/jellyfin/jellyfin-web/blob/bef977062e7cde96716efa23a98d06c4285e8f28/src/controllers/list.js#L308-L315
