### ISSUE TITLE
Multiple issues with Cast 

### ISSUE THREAD

**Issue by Raul824** [jellyfin/jellyfin-web#1449]
Below are the multiple issues i have observed with Casting

1. When casting to a remote computer or Chromecast  pressing the forward 30 sec or reverse 30 second will cause the end of stream in jellyfin-mpv-shim the video starts playing from the beginning.
Clicking on seek baar seems to work in forwarding and moving.

2. After casting device selected the web browser isn't allowing the drop down upon clicking the cast icon which used to give disconnect or remote control option in 10.5.5

3. Clicking on sound isn't putting the casting device to mute not even the button logo changing upon clicking.

I think this has to do with below as the browser isn't able to send playback reporting progress to casting device.
```
[2020-06-20 06:17:17.620 +00:00] [ERR] [91] Emby.Server.Implementations.Session.SessionManager: Error in event handler
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<MediaBrowser.Controller.Entities.User> MediaBrowser.Controller.Library.PlaybackProgressEventArgs.get_Users()'.
   at Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint._sessionManager_PlaybackStart(Object sender, PlaybackProgressEventArgs e)
   at MediaBrowser.Common.Events.EventHelper.<>c__DisplayClass1_0`1.<QueueEventIfNotNull>b__0()
[2020-06-20 06:17:17.621 +00:00] [ERR] [137] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "The operation was canceled". 8a363f85-5345-62d4-5267-52800b5db2dd/stream?static=true&MediaSourceId=8a363f85534562d4526752800b5db2dd"
[2020-06-20 06:17:17.936 +00:00] [ERR] [91] Emby.Server.Implementations.Session.SessionManager: Error reporting playback progress
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<MediaBrowser.Controller.Entities.User> MediaBrowser.Controller.Library.PlaybackProgressEventArgs.get_Users()'.
   at Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint._sessionManager_PlaybackProgress(Object sender, PlaybackProgressEventArgs e)
   at Emby.Server.Implementations.Session.SessionManager.OnPlaybackProgress(PlaybackProgressInfo info, Boolean isAutomated)
   at MediaBrowser.Controller.Session.SessionInfo.OnProgressTimerCallback(Object state)
```

**Comment by ferferga** [comment]
@Raul824 is this happening with current unstables?

**Comment by hamburglar2160** [comment]
#2 has always been the case since at least 10.4, that menu needs to be burned to the ground. The page requires several refreshes after interacting with the menu on disconnect.

**Comment by iwalton3** [comment]
Item 1 is caused by https://github.com/jellyfin/jellyfin-web/issues/1790 and has details on the cause and possible solution.
