### ISSUE TITLE
Available plugin versions appear as "undefined", installation fails

### ISSUE THREAD

**Issue by KristupasSavickas** [jellyfin/jellyfin-web#1623]
**Describe the bug**

I was using Jellyfin 10.6.0 unstable before the release, so its possible that configuration might be corrupt.
The migration to add the default plugin repository didn't happen for me, so I did it manually:
![Screenshot_20200722_152359](https://user-images.githubusercontent.com/1362643/88176033-5fbd6b80-cc2f-11ea-8e85-245c3a744904.png)

The plugins are discovered as expected, but all available versions are shown as `undefined`.
Installation fails with an infinitely spinning loading indicator, because `undefined` is passed to the server:
`https://jellyfin.REDACTED.lt/Packages/Installed/Trakt?AssemblyGuid=4fe3201e-d6ae-4f2e-8917-e12bda571281&version=undefined`

![Screenshot_20200722_152100](https://user-images.githubusercontent.com/1362643/88175911-2e44a000-cc2f-11ea-83ad-0ed880d85583.png)

**Expected behavior**

**Logs**
Web:
```
bundle.js?v=20:266 POST https://jellyfin.REDACTED.lt/Packages/Installed/Trakt?AssemblyGuid=4fe3201e-d6ae-4f2e-8917-e12bda571281&version=undefined 400
w @ bundle.js?v=20:266
value @ bundle.js?v=20:266
value @ bundle.js?v=20:266
value @ bundle.js?v=20:266
alertCallback @ add.js?v=20:1
performInstallation @ add.js?v=20:1
(anonymous) @ add.js?v=20:1
Promise.then (async)
(anonymous) @ add.js?v=20:1
dispatch @ bundle.js?v=20:25
m.handle @ bundle.js?v=20:25
/web/index.html?#!/addplugin.html?name=Trakt&guid=4fe3201e-d6ae-4f2e-8917-e12bda571281:1 Uncaught (in promise) Response {type: "basic", url: "https://jellyfin.REDACTED.lt/Packages/Installed/Trakt…01e-d6ae-4f2e-8917-e12bda571281&version=undefined", redirected: false, status: 400, ok: false, …}
Promise.then (async)
alertCallback @ add.js?v=20:1
performInstallation @ add.js?v=20:1
(anonymous) @ add.js?v=20:1
Promise.then (async)
(anonymous) @ add.js?v=20:1
dispatch @ bundle.js?v=20:25
m.handle @ bundle.js?v=20:25
```

Server:
```
[2020-07-22 15:24:27.855 +03:00] [WRN] [33] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "88.119.128.229". Time (slow): 0:00:00.7800478. "http://jellyfin.REDACTED.lt/Packages?PackageType=UserInstalled"
[2020-07-22 15:24:46.374 +03:00] [ERR] [36] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://jellyfin.REDACTED.lt/Packages/Installed/Trakt?AssemblyGuid=4fe3201e-d6ae-4f2e-8917-e12bda571281&version=undefined"
System.ArgumentException: Version string portion was too short or too long. (Parameter 'input')
   at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
   at System.Version.Parse(String input)
   at MediaBrowser.Api.PackageService.Post(InstallPackage request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

```

**Screenshots**

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: [e.g. 10.0.1]

**Additional context**

**Comment by MrTimscampi** [comment]
You are using the old manifest URL.

You need to remove the old repository and add this one: `https://repo.jellyfin.org/releases/plugin/manifest-stable.json`

**Comment by KristupasSavickas** [comment]
Thanks, this worked.
