### ISSUE TITLE
All requests returning 500 with "Error processing request"

### ISSUE THREAD

**Issue by goodevilgenius** [jellyfin/jellyfin-web#1943]
**Describe The Bug**

All requests are returning 500, with the body reading "Error processing request."

**Steps To Reproduce**

1. Make request to any route on jellyfin-web.

```
$ http http://localhost:8096/web
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type, Authorization, Range, X-MediaBrowser-Token, X-Emby-Authorization, Cookie
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
Access-Control-Allow-Origin: localhost:8096
Content-Encoding: gzip
Content-Type: text/plain
Date: Mon, 21 Sep 2020 21:47:58 GMT
Server: Kestrel
Transfer-Encoding: chunked
Vary: Accept-Encoding

Error processing request.
```

**Expected Behavior**

The web interface would work.

**Logs**
```
[2020-09-21 16:48:51.125 -05:00] [ERR] [18] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: "http://localhost:8096/web"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.ResourceFileManager.GetResourcePath(String basePath, String virtualPath)
   at MediaBrowser.WebDashboard.Api.DashboardService.Get(GetDashboardResource request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**System (please complete the following information):**
 - Platform: Fedora Linux 5.7.11-100.fc31.x86_64
 - Browser: Firefox
 - Jellyfin Version: 10.6.4

**Additional Context**

It was working until I made a change to one of my playlists. I'm not sure if that's related.

**Comment by jolny** [comment]
@goodevilgenius try from aonther browser, and/or try clearing your cache. I have this same error in Firefox right now, but it works in Brave. :smile: 
I'm thinking, maybe there's some kind of error with the session cookie?

**Comment by goodevilgenius** [comment]
I tried multiple browsers.

Then it just fixed itself after about a week. No idea what the cause was or how it fixed itself.

**Comment by jolny** [comment]
I see!
I noticed the URL was a bit weird in my case, the #! characters were in a different place, so I tried removing the whole path (after the domain and port) and that fixed it for me :)
