### ISSUE TITLE
Unable to access People (Cast & Crew) on newly created

### ISSUE THREAD

**Issue by spirillen** [jellyfin/jellyfin-web#2606]
**Describe The Bug**
There are to cases, but the log/actions are the same.

**Steps To Reproduce**
1. Add a new person/people/Cast & Crew
    ![image](https://user-images.githubusercontent.com/44526987/115594398-fb226080-a2d5-11eb-95fb-9b1cbf686b62.png)
2. Now try to do anything, at all  with the person just added and you'll get stocked on the spinning circle

Situation 2
1. Moved the metadata dir to new location
2. You'll loose all previously modified information (In my case 100's)
3. Try pick one "existing" person for altering/search and again nothing is happening.

**Expected Behavior**
Really :thinking: 

**Logs**
<description><summary>Log</summary>

Apr 21 19:19:19 hostsname jellyfin[4324]: [19:19:19] [ERR] Error processing request. URL GET /Users/RANDOM/Items/RANDOM.
Apr 21 19:19:19 hostsname jellyfin[4324]: System.NullReferenceException: Object reference not set to an instance of an object.
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDtoInternal(BaseItem item, DtoOptions options, User user, BaseItem owner)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDto(BaseItem item, DtoOptions options, User user, BaseItem owner)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Jellyfin.Api.Controllers.UserLibraryController.GetItem(Guid userId, Guid itemId)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at lambda_method551(Closure , Object )
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Apr 21 19:19:19 hostsname jellyfin[4324]: --- End of stack trace from previous location ---
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Apr 21 19:19:19 hostsname jellyfin[4324]: --- End of stack trace from previous location ---
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
Apr 21 19:19:19 hostsname jellyfin[4324]:    at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)

Apr 21 19:21:23 hostsname jellyfin[4324]: [19:21:23] [ERR] Error processing request. URL GET /Users/RANDOM-ID/Items/ID.
Apr 21 19:21:23 hostsname jellyfin[4324]: System.NullReferenceException: Object reference not set to an instance of an object.
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDtoInternal(BaseItem item, DtoOptions options, User user, BaseItem owner)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDto(BaseItem item, DtoOptions options, User user, BaseItem owner)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Jellyfin.Api.Controllers.UserLibraryController.GetItem(Guid userId, Guid itemId)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at lambda_method551(Closure , Object )
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Apr 21 19:21:23 hostsname jellyfin[4324]: --- End of stack trace from previous location ---
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Apr 21 19:21:23 hostsname jellyfin[4324]: --- End of stack trace from previous location ---
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
Apr 21 19:21:23 hostsname jellyfin[4324]:    at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)

</description>

**Screenshots**
![image](https://user-images.githubusercontent.com/44526987/115595219-f5794a80-a2d6-11eb-9dd2-00ba785348b2.png)

**System (please complete the following information):**
 - Platform: Ubunt 20.04.1 X64
 - Browser: Firefox, Palemoon
 - Jellyfin Version: 10.7.2

**Additional Context**
The first screenshot is from an existing person, however it would be the same for any newly added in any folder.

```bash
New location (Rsync-ed)
l metadata/People/N/Nicole\ Kidman/
total 196K
-rwxrwxr-x 1 jellyfin jellyfin 195K Apr 15 00:05 poster.png
```

```bash
old location
l /var/lib/jellyfin/metadata/People/N/Nicole\ Kidman/
total 196K
-rwxrwxr-x 1 joakim jellyfin 195K Apr 15 00:05 poster.png
```

**Comment by spirillen** [comment]
Bump

**Comment by spirillen** [comment]
ping

**Comment by spirillen** [comment]
@Pong

**Comment by spirillen** [comment]
@ping

**Comment by thornbill** [comment]
How are you adding a person when you encounter this? (Trying to find an easy way to reproduce this.) I know the image not displaying initially is a known bug in server, but I had overlooked the other part of this issue.

**Comment by spirillen** [comment]
As I recall this one, it is related to when you moves the data folder to new location, in this case I moved it from my SSD to my storage (raid 5) and changed the storage location in the config file and restarted jellyfin.

This is probably the closed I come to recall this issue
