### ISSUE TITLE
10.7.5-1 Memory Leak?

### ISSUE THREAD

**Issue by iPwnWolf** [jellyfin/jellyfin-web#2669]
**Describe The Bug**
Today I updated my Jellyfin Version from 10.7.2 to 10.7.5-1. After that my playback was laging really bad and I saw high memory usage. When restarting jellyfin the memory filled up again quickly and it was just as lagy.
Then I decided to restart the whole server and now Jellyfin-Web is loading REALLY SLOW (about 10 minutes to show anything). Same issue in the app. Also same issue when loading the site with the ip directly.

**Steps To Reproduce**
1. update from V. 10.7.2 to V. 10.7.5-1

**Expected Behavior**
Working website

**Logs**

<details>
<summary>Log</summary>

```
[2021-05-12 11:47:48.334 +02:00] [WRN] Unable to find linked item at path "/media/media4TB/Filme/How to Train Your Dragon - The Hidden World (2019)/How to Train Your Dragon - The Hidden World (2019) Bluray-1080p.mkv"
[2021-05-12 11:47:48.370 +02:00] [WRN] Slow HTTP Response from "http://192.168.178.94:8096/users/7e23b1734cc54ed9b3b2eb1b78788315/items?Recursive=True&IncludeItemTypes=Movie&Fields=ProviderIds,Overview&startIndex=0&limit=200&IsVirtualItem=False" to "192.168.178.94" in 0:40:01.1349789 with Status Code 200
[2021-05-12 11:53:34.701 +02:00] [WRN] As of "00:05:43.8632170", the heartbeat has been running for "00:00:01" which is longer than "05/12/2021 09:47:50 +00:00". This could be caused by thread pool starvation.
[2021-05-12 11:53:34.993 +02:00] [ERR] Error in GetFilteredFileSystemEntries isPhysicalRoot: False IsVf: False
System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/pi_NCSimon/Handy'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.<GetFileSystemEntries>b__5_0(String p)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveShortcuts)
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePath(FileSystemMetadata fileInfo, IDirectoryService directoryService, IItemResolver[] resolvers, Folder parent, String collectionType, LibraryOptions libraryOptions)
[2021-05-12 11:53:35.044 +02:00] [ERR] Error in "PlaylistResolver" resolving "/media/pi_NCSimon/Handy"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/pi_NCSimon/Handy'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.Library.Resolvers.PlaylistResolver.Resolve(ItemResolveArgs args)
   at Emby.Server.Implementations.Library.Resolvers.ItemResolver`1.MediaBrowser.Controller.Resolvers.IItemResolver.ResolvePath(ItemResolveArgs args)
   at Emby.Server.Implementations.Library.LibraryManager.Resolve(ItemResolveArgs args, IItemResolver resolver)
[2021-05-12 11:53:35.188 +02:00] [ERR] Error in GetFilteredFileSystemEntries isPhysicalRoot: False IsVf: False
System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/pi_NCSimon/PC'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.<GetFileSystemEntries>b__5_0(String p)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MediaBrowser.Controller.IO.FileData.GetFilteredFileSystemEntries(IDirectoryService directoryService, String path, IFileSystem fileSystem, IServerApplicationHost appHost, ILogger logger, ItemResolveArgs args, Int32 flattenFolderDepth, Boolean resolveShortcuts)
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePath(FileSystemMetadata fileInfo, IDirectoryService directoryService, IItemResolver[] resolvers, Folder parent, String collectionType, LibraryOptions libraryOptions)
[2021-05-12 11:53:35.189 +02:00] [ERR] Error in "PlaylistResolver" resolving "/media/pi_NCSimon/PC"
System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/pi_NCSimon/PC'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.Library.Resolvers.PlaylistResolver.Resolve(ItemResolveArgs args)
   at Emby.Server.Implementations.Library.Resolvers.ItemResolver`1.MediaBrowser.Controller.Resolvers.IItemResolver.ResolvePath(ItemResolveArgs args)
   at Emby.Server.Implementations.Library.LibraryManager.Resolve(ItemResolveArgs args, IItemResolver resolver)
[2021-05-12 11:53:37.055 +02:00] [ERR] Cannot compute blurhash for "/media/media8TB/Filme/Ava (2020)/fanart.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2021-05-12 11:53:37.270 +02:00] [ERR] Cannot compute blurhash for "/media/media8TB/Filme/The Incredible Hulk (2008)/fanart.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2021-05-12 11:53:39.274 +02:00] [ERR] Error retrieving children folder
System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/pi_NCSimon/Handy'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.<GetFileSystemEntries>b__5_0(String p)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MediaBrowser.Controller.Entities.Folder.GetNonCachedChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
[2021-05-12 11:53:39.379 +02:00] [ERR] Cannot get image dimensions for "/var/lib/jellyfin/data/collections/F"
System.IO.FileNotFoundException: File not found
File name: '/var/lib/jellyfin/data/collections/F'
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageSize(String path)
   at Emby.Drawing.ImageProcessor.GetImageDimensions(BaseItem item, ItemImageInfo info)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
[2021-05-12 11:53:39.533 +02:00] [ERR] Error retrieving children folder
System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/pi_NCSimon/PC'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.<GetFileSystemEntries>b__5_0(String p)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MediaBrowser.Controller.Entities.Folder.GetNonCachedChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, CancellationToken cancellationToken, Boolean recursive, Boolean refreshChildMetadata, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService)
[2021-05-12 11:57:00.767 +02:00] [WRN] As of "00:03:20.2342416", the heartbeat has been running for "00:00:01" which is longer than "05/12/2021 09:53:40 +00:00". This could be caused by thread pool starvation.
[2021-05-12 11:59:58.518 +02:00] [WRN] As of "00:02:54.6449847", the heartbeat has been running for "00:00:01" which is longer than "05/12/2021 09:57:03 +00:00". This could be caused by thread pool starvation.
[2021-05-12 12:05:31.549 +02:00] [WRN] As of "00:05:29.9912162", the heartbeat has been running for "00:00:01" which is longer than "05/12/2021 10:00:01 +00:00". This could be caused by thread pool starvation.
[2021-05-12 12:05:33.543 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:00:00.8719733 with Status Code 200
[2021-05-12 12:05:33.543 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:00:01.0974944 with Status Code 200
[2021-05-12 12:05:33.419 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:00:01.0976157 with Status Code 200
[2021-05-12 12:05:33.544 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:00:01.0976279 with Status Code 200
[2021-05-12 12:05:33.421 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:00:01.0976401 with Status Code 200
[2021-05-12 12:11:42.422 +02:00] [WRN] As of "00:05:31.4103172", the heartbeat has been running for "00:00:01" which is longer than "05/12/2021 10:06:10 +00:00". This could be caused by thread pool starvation.
[2021-05-12 12:11:42.553 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:05:54.7850894 with Status Code 200
[2021-05-12 12:11:44.247 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:00:01.7429683 with Status Code 200
[2021-05-12 12:11:44.251 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "77.0.209.143" in 0:00:01.743797 with Status Code 200
[2021-05-12 12:11:44.495 +02:00] [WRN] Slow HTTP Response from "http://192.168.178.94:8096/users/7e23b1734cc54ed9b3b2eb1b78788315/items?Recursive=True&IncludeItemTypes=Episode&Fields=ProviderIds&startIndex=0&limit=200&IsVirtualItem=False" to "192.168.178.94" in 0:00:01.956756 with Status Code 200
[2021-05-12 12:11:45.483 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:00:02.9792008 with Status Code 200
[2021-05-12 12:11:45.503 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:00:02.9987108 with Status Code 200
[2021-05-12 12:21:04.404 +02:00] [WRN] As of "00:05:37.0985061", the heartbeat has been running for "00:00:01" which is longer than "05/12/2021 10:12:22 +00:00". This could be caused by thread pool starvation.
[2021-05-12 12:27:02.901 +02:00] [WRN] Slow HTTP Response from "http://192.168.178.94:8096/web/index.html" to "192.168.178.101" in 0:03:12.6874715 with Status Code 200
[2021-05-12 12:27:03.105 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:05:58.618448 with Status Code 200
[2021-05-12 12:27:03.116 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:05:58.6328783 with Status Code 200
[2021-05-12 12:27:03.121 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:05:58.6383108 with Status Code 200
[2021-05-12 12:27:03.298 +02:00] [INF] Defined LAN addresses : "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-05-12 12:27:03.298 +02:00] [INF] Defined LAN exclusions : "[]"
[2021-05-12 12:27:03.298 +02:00] [INF] Using LAN addresses: "[127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2021-05-12 12:30:25.948 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:09:21.4326933 with Status Code 200
[2021-05-12 12:30:25.948 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:09:21.4294079 with Status Code 200
[2021-05-12 12:33:50.382 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/auto00cd17f35016e45af8d4997c1a37d95c.woff2" to "77.0.209.143" in 0:00:00.5755368 with Status Code 404
[2021-05-12 12:37:14.145 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:03:24.3238654 with Status Code 200
[2021-05-12 12:37:14.145 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/main.4b4b736dbefe7c3a90ec.bundle.js" to "77.0.209.143" in 0:03:24.3237114 with Status Code 200
[2021-05-12 12:52:52.581 +02:00] [WRN] Slow HTTP Response from "http://192.168.178.94:8096/web/index.html" to "192.168.178.101" in 0:02:43.0377138 with Status Code 200
[2021-05-12 12:52:52.581 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/main.4b4b736dbefe7c3a90ec.bundle.js" to "77.0.209.143" in 0:02:43.0313772 with Status Code 200
[2021-05-12 12:56:12.009 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:03:19.4249812 with Status Code 200
[2021-05-12 12:56:12.045 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:03:19.3921978 with Status Code 200
[2021-05-12 12:56:11.998 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:03:19.3890873 with Status Code 200
[2021-05-12 12:56:13.255 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "77.0.209.143" in 0:00:01.2549988 with Status Code 304
[2021-05-12 12:56:13.261 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:00:01.2612229 with Status Code 200
[2021-05-12 12:56:13.261 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:00:01.261584 with Status Code 200
[2021-05-12 12:56:13.262 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:00:01.2621741 with Status Code 200
[2021-05-12 12:59:31.549 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/auto013d88d33df6093c608e5fc9c6de13ef.woff2" to "77.0.209.143" in 0:00:01.7371321 with Status Code 404
[2021-05-12 12:59:31.550 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:00:01.7408253 with Status Code 200
[2021-05-12 12:59:31.549 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/auto00cd17f35016e45af8d4997c1a37d95c.woff2" to "77.0.209.143" in 0:00:01.737127 with Status Code 404
[2021-05-12 12:59:31.551 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:00:01.7417005 with Status Code 200
[2021-05-12 12:59:31.549 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/auto0095962de230e8e76d21c78c2130ce89.woff2" to "77.0.209.143" in 0:00:01.7371739 with Status Code 404
[2021-05-12 13:02:48.472 +02:00] [WRN] Slow HTTP Response from "http://192.168.178.94:8096/web/config.json" to "192.168.178.101" in 0:03:18.6124462 with Status Code 200
[2021-05-12 13:02:48.472 +02:00] [WRN] Slow HTTP Response from "http://192.168.178.94:8096/web/config.json" to "192.168.178.101" in 0:03:16.9160634 with Status Code 200
[2021-05-12 13:02:48.472 +02:00] [WRN] Slow HTTP Response from "http://192.168.178.94:8096/web/config.json" to "192.168.178.101" in 0:03:18.6149653 with Status Code 200
[2021-05-12 13:07:28.981 +02:00] [WRN] Slow HTTP Response from "http://192.168.178.94:8096/web/themes/dark/theme.css" to "192.168.178.101" in 0:04:39.3344474 with Status Code 200
[2021-05-12 13:07:33.065 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:00:04.0602443 with Status Code 200
[2021-05-12 13:07:33.065 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:00:04.0210474 with Status Code 200
[2021-05-12 13:07:33.065 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:00:04.0612486 with Status Code 200
[2021-05-12 13:07:33.065 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/web/index.html" to "78.34.79.231" in 0:00:04.0269812 with Status Code 200
[2021-05-12 13:07:33.088 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/System/Info/Public" to "77.0.209.143" in 0:04:43.4703653 with Status Code 200
[2021-05-12 13:07:33.097 +02:00] [WRN] Slow HTTP Response from "http://192.168.178.94:8096/System/Info/Public" to "192.168.178.101" in 0:04:43.478674 with Status Code 200
[2021-05-12 13:07:35.890 +02:00] [INF] WS "77.0.209.143" request
[2021-05-12 13:07:36.208 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/Sessions/Capabilities/Full" to "77.0.209.143" in 0:00:00.6528732 with Status Code 204
[2021-05-12 13:07:36.221 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/DisplayPreferences/usersettings?userId=7e23b1734cc54ed9b3b2eb1b78788315&client=emby" to "77.0.209.143" in 0:00:00.661663 with Status Code 200
[2021-05-12 13:07:36.582 +02:00] [WRN] Slow HTTP Response from "http://192.168.178.94:8096/users/7e23b1734cc54ed9b3b2eb1b78788315/items?Recursive=True&IncludeItemTypes=Episode&Fields=ProviderIds&startIndex=0&limit=200&IsVirtualItem=False" to "192.168.178.94" in 0:00:07.5532804 with Status Code 200
[2021-05-12 13:07:37.431 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/Users/7e23b1734cc54ed9b3b2eb1b78788315/Views" to "77.0.209.143" in 0:00:00.7372889 with Status Code 200
[2021-05-12 13:07:38.050 +02:00] [WRN] Slow HTTP Response from "http://192.168.178.94:8096/users/7e23b1734cc54ed9b3b2eb1b78788315/items?Recursive=True&IncludeItemTypes=Episode&Fields=ProviderIds&startIndex=201&limit=200&IsVirtualItem=False" to "192.168.178.94" in 0:00:00.5254546 with Status Code 200
[2021-05-12 13:07:38.161 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/LiveTv/Programs/Recommended?userId=7e23b1734cc54ed9b3b2eb1b78788315&IsAiring=true&limit=1&ImageTypeLimit=1&EnableImageTypes=Primary%2CThumb%2CBackdrop&EnableTotalRecordCount=false&Fields=ChannelInfo%2CPrimaryImageAspectRatio" to "77.0.209.143" in 0:00:00.5246938 with Status Code 200
[2021-05-12 13:10:53.845 +02:00] [INF] Lost 1 WebSockets.
[2021-05-12 13:10:53.845 +02:00] [WRN] As of "00:03:13.6229749", the heartbeat has been running for "00:00:01" which is longer than "05/12/2021 11:07:40 +00:00". This could be caused by thread pool starvation.
[2021-05-12 13:10:54.107 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/Users/7e23b1734cc54ed9b3b2eb1b78788315/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Video" to "77.0.209.143" in 0:03:15.8811701 with Status Code 200
[2021-05-12 13:10:54.743 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/Users/7e23b1734cc54ed9b3b2eb1b78788315/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=7a2175bccb1f1a94152cbd2b2bae8f6d" to "77.0.209.143" in 0:03:16.5119817 with Status Code 200
[2021-05-12 13:10:54.753 +02:00] [WRN] Slow HTTP Response from "http://filme.serverwolf.de/Users/7e23b1734cc54ed9b3b2eb1b78788315/Items/Latest?Limit=16&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo%2CPath&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&ParentId=2322d4a7f33526fa54da46d53b3d1a19" to "77.0.209.143" in 0:03:16.5240232 with Status Code 200
```

</details>

**Screenshots**
Pay attention to the memory usage...
![image](https://user-images.githubusercontent.com/31454341/117965537-28858b80-b323-11eb-894a-c3a1312a85c6.png)
![image](https://user-images.githubusercontent.com/31454341/117964611-1b1bd180-b322-11eb-8e96-5c14d343471d.png)
![image](https://user-images.githubusercontent.com/31454341/117967472-5ff53780-b325-11eb-9766-b63387374e88.png)

**System (please complete the following information):**
 - Platform: Debian 10.9 64bit
 - Browser: any
 - Jellyfin 10.7.5-1

**Comment by iPwnWolf** [comment]
I think I was able to resolve the issue by uninstalling the Anime Plugin.
