### ISSUE TITLE
Web UI requests the first segment when resuming a video

### ISSUE THREAD

**Issue by EraYaN** [jellyfin/jellyfin-web#457]
**Describe the bug**
It sends a request for 0.ts even if the resume point is really in 31.ts. This results in the server quickly calling ffmpeg and killing it again, showing this behaviour: https://github.com/jellyfin/jellyfin/issues/1733

**To Reproduce**
1. Resume any video.
2. Monitor the client/server logs.

**Expected behavior**
It should immediately request the 31.ts file and not first the first segment.

**Logs**
*Server*
```
[17:36:33] [INF] User policy for User. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[17:36:33] [INF] Profile: Unknown Profile, Path: C:\movie.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[17:36:33] [INF] Profile: Unknown Profile, No direct play profiles found for Path: C:\movie.mkv
[17:36:33] [INF] Profile: Unknown Profile, Path: C:\movie.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[17:36:33] [INF] Profile: Unknown Profile, No direct play profiles found for Path: C:\movie.mkv
[17:36:33] [INF] Profile: Unknown Profile, Path: C:\movie.mkv, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[17:36:33] [INF] Profile: Unknown Profile, No direct play profiles found for Path: C:\movie.mkv
[17:36:34] [INF] ffmpeg.exe -f matroska,webm -i file:"C:\movie.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 114713710 -bufsize 229427420 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames:0 "expr:gte(t,0+n_forced*3)" -copyts -vsync -1 -codec:a:0 aac -strict experimental -ac 2 -ab 384000 -af "volume=2" -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 0 -segment_list "C:\jellyfin\transcoding-temp\14aed8b63968012e59cfce3384f61db8.m3u8" -y "C:\jellyfin\transcoding-temp\14aed8b63968012e59cfce3384f61db8%d.ts"
[17:36:37] [INF] returning C:\jellyfin\transcoding-temp\14aed8b63968012e59cfce3384f61db80.ts
[17:36:37] [WRN] HTTP Response 200 to 127.0.0.1. Time (slow): 0:00:03.1664686. http://localhost:8096/videos/e83b9ca8-279b-6d25-7743-7cfa21fb7305/hls1/main/0.ts?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NjUuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC82NS4wfDE1NDY5NTMzOTIzMjQ1&MediaSourceId=e83b9ca8279b6d2577437cfa21fb7305&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=139616000&AudioBitrate=384000&PlaySessionId=8cfb0a088d2b4ae4a415b4c80d188bcf&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=26b7d58089fd340a54138db627fc658e&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51
[17:36:37] [INF] Stopping ffmpeg process with q command for C:\jellyfin\transcoding-temp\14aed8b63968012e59cfce3384f61db8.m3u8
[17:36:38] [WRN] HTTP Response 500 to 127.0.0.1. Time (slow): 0:00:00.6492525. http://localhost:8096/videos/e83b9ca8-279b-6d25-7743-7cfa21fb7305/hls1/main/1.ts?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NjUuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC82NS4wfDE1NDY5NTMzOTIzMjQ1&MediaSourceId=e83b9ca8279b6d2577437cfa21fb7305&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=139616000&AudioBitrate=384000&PlaySessionId=8cfb0a088d2b4ae4a415b4c80d188bcf&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=26b7d58089fd340a54138db627fc658e&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51
[17:36:38] [INF] FFMpeg exited with code 0
[17:36:38] [ERR] Error killing transcoding job for C:\jellyfin\transcoding-temp\14aed8b63968012e59cfce3384f61db8.m3u8
System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_HasExited()
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ExitCode()
   at MediaBrowser.Api.Playback.BaseStreamingService.OnFfMpegProcessExited(Process process, TranscodingJob job, StreamState state) in F:\jellyfin-src\MediaBrowser.Api\Playback\BaseStreamingService.cs:line 359
   at MediaBrowser.Api.Playback.BaseStreamingService.<>c__DisplayClass63_0.<StartFfMpeg>b__0(Object sender, EventArgs args) in F:\jellyfin-src\MediaBrowser.Api\Playback\BaseStreamingService.cs:line 277
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Diagnostics.Process.WaitForExit(Int32 milliseconds)
   at MediaBrowser.Api.ApiEntryPoint.KillTranscodingJob(TranscodingJob job, Boolean closeLiveStream, Func`2 delete) in F:\jellyfin-src\MediaBrowser.Api\ApiEntryPoint.cs:line 607
[17:36:38] [INF] ffmpeg.exe -ss 00:01:33.000 -f matroska,webm -i file:"C:\movie.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -pix_fmt yuv420p -preset veryfast -crf 23 -maxrate 114713710 -bufsize 229427420 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames:0 "expr:gte(t,93+n_forced*3)" -copyts -vsync -1 -codec:a:0 aac -strict experimental -ac 2 -ab 384000 -af "volume=2" -f segment -max_delay 5000000 -avoid_negative_ts disabled -start_at_zero -segment_time 3  -individual_header_trailer 0 -segment_format mpegts -segment_list_type m3u8 -segment_start_number 31 -segment_list "C:\jellyfin\transcoding-temp\14aed8b63968012e59cfce3384f61db8.m3u8" -y "C:\jellyfin\transcoding-temp\14aed8b63968012e59cfce3384f61db8%d.ts"
[17:36:38] [INF] returning C:\jellyfin\transcoding-temp\14aed8b63968012e59cfce3384f61db831.ts
[17:36:43] [WRN] HTTP Response 200 to 127.0.0.1. Time (slow): 0:00:05.5086517. http://localhost:8096/videos/e83b9ca8-279b-6d25-7743-7cfa21fb7305/hls1/main/31.ts?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NjUuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC82NS4wfDE1NDY5NTMzOTIzMjQ1&MediaSourceId=e83b9ca8279b6d2577437cfa21fb7305&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=139616000&AudioBitrate=384000&PlaySessionId=8cfb0a088d2b4ae4a415b4c80d188bcf&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=26b7d58089fd340a54138db627fc658e&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51
[17:36:43] [WRN] HTTP Response 200 to 127.0.0.1. Time (slow): 0:00:00.656059. http://localhost:8096/videos/e83b9ca8-279b-6d25-7743-7cfa21fb7305/hls1/main/32.ts?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NjUuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC82NS4wfDE1NDY5NTMzOTIzMjQ1&MediaSourceId=e83b9ca8279b6d2577437cfa21fb7305&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=139616000&AudioBitrate=384000&PlaySessionId=8cfb0a088d2b4ae4a415b4c80d188bcf&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=26b7d58089fd340a54138db627fc658e&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51
[17:36:44] [WRN] HTTP Response 200 to 127.0.0.1. Time (slow): 0:00:00.7745577. http://localhost:8096/videos/e83b9ca8-279b-6d25-7743-7cfa21fb7305/hls1/main/33.ts?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NjUuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC82NS4wfDE1NDY5NTMzOTIzMjQ1&MediaSourceId=e83b9ca8279b6d2577437cfa21fb7305&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=139616000&AudioBitrate=384000&PlaySessionId=8cfb0a088d2b4ae4a415b4c80d188bcf&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=26b7d58089fd340a54138db627fc658e&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51
[17:36:45] [INF] Stopping ffmpeg process with q command for C:\jellyfin\transcoding-temp\14aed8b63968012e59cfce3384f61db8.m3u8
[17:36:46] [WRN] HTTP Response 500 to 127.0.0.1. Time (slow): 0:00:01.4967939. http://localhost:8096/videos/e83b9ca8-279b-6d25-7743-7cfa21fb7305/hls1/main/34.ts?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NjUuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC82NS4wfDE1NDY5NTMzOTIzMjQ1&MediaSourceId=e83b9ca8279b6d2577437cfa21fb7305&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=139616000&AudioBitrate=384000&PlaySessionId=8cfb0a088d2b4ae4a415b4c80d188bcf&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=26b7d58089fd340a54138db627fc658e&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51
[17:36:46] [INF] FFMpeg exited with code 0
[17:36:46] [INF] Deleting partial stream file(s) C:\jellyfin\transcoding-temp\14aed8b63968012e59cfce3384f61db8.m3u8
[17:36:47] [INF] Playback stopped reported by app Jellyfin Web 10.3.6 playing Movie. Stopped at 97264 ms
[17:36:47] [WRN] HTTP Response 204 to 127.0.0.1. Time (slow): 0:00:01.9721571. http://localhost:8096/Sessions/Playing/Stopped
```
*Client*
```
Requesting url without automatic networking: http://localhost:8096/Users/7372c70e9ae5440bb3967c2a52632d32/Items/e83b9ca8279b6d2577437cfa21fb7305 apiclientcore.js:264:21
Requesting url without automatic networking: http://localhost:8096/Items/e83b9ca8279b6d2577437cfa21fb7305/PlaybackInfo?UserId=7372c70e9ae5440bb3967c2a52632d32&StartTimeTicks=952777070&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000 apiclientcore.js:264:21
playing url: http://localhost:8096/videos/e83b9ca8-279b-6d25-7743-7cfa21fb7305/master.m3u8?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NjUuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC82NS4wfDE1NDY5NTMzOTIzMjQ1&MediaSourceId=e83b9ca8279b6d2577437cfa21fb7305&VideoCodec=h264&AudioCodec=aac&AudioStreamIndex=1&VideoBitrate=139616000&AudioBitrate=384000&PlaySessionId=8cfb0a088d2b4ae4a415b4c80d188bcf&api_key=d307067cdf66428eb32417f843095d50&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=26b7d58089fd340a54138db627fc658e&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51 plugin.js:474:21
appRouter - processing path request /web#!/videoosd.html appRouter.js:390:17
appRouter - user is authenticated appRouter.js:411:21
appRouter - proceeding to /web#!/videoosd.html appRouter.js:428:17
Active player: {"name":"Html Video Player","id":"htmlvideoplayer","playerName":"Html Video Player","playableMediaTypes":[false,true,false,false],"isLocalPlayer":true,"supportedCommands":["GoHome","GoToSettings","VolumeUp","VolumeDown","Mute","Unmute","ToggleMute","SetVolume","SetAudioStreamIndex","SetSubtitleStreamIndex","SetMaxStreamingBitrate","DisplayContent","GoToSearch","DisplayMessage","SetRepeatMode","PlayMediaSource","PlayTrailers","ToggleFullscreen","SetBrightness"]} playbackmanager.js:1033:25
Requesting url without automatic networking: http://localhost:8096/Sessions/Playing apiclientcore.js:264:21
Setting new text track index to: 2 plugin.js:1262:21
currentTrack id: textTrack2 plugin.js:1295:25
expectedId: textTrack-1--currentTrack.Id:textTrack2 plugin.js:1299:25
Setting track 0 mode to: 0 plugin.js:1320:25
HLS Error: Type: mediaError Details: bufferStalledError Fatal: false htmlMediaHelper.js:310:21
HLS Error: Type: mediaError Details: bufferNudgeOnStall Fatal: false htmlMediaHelper.js:310:21
Requesting url without automatic networking: http://localhost:8096/Sessions/Playing/Progress apiclientcore.js:264:21
appRouter - processing path request /web#!/home.html appRouter.js:390:17
appRouter - user is authenticated appRouter.js:411:21
appRouter - proceeding to /web#!/home.html appRouter.js:428:17
Requesting url without automatic networking: http://localhost:8096/Sessions/Playing/Stopped apiclientcore.js:264:21
Requesting url without automatic networking: http://localhost:8096/Users/7372c70e9ae5440bb3967c2a52632d32/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Video apiclientcore.js:264:21
Requesting url without automatic networking: http://localhost:8096/Users/7372c70e9ae5440bb3967c2a52632d32/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Audio apiclientcore.js:264:21
Requesting url without automatic networking: http://localhost:8096/Shows/NextUp?Limit=24&Fields=PrimaryImageAspectRatio%2CSeriesInfo%2CDateCreated%2CBasicSyncInfo&UserId=7372c70e9ae5440bb3967c2a52632d32&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&EnableTotalRecordCount=false apiclientcore.js:264:21
app is hidden apphost.js:203:21
Requesting url without automatic networking: http://localhost:8096/Users/7372c70e9ae5440bb3967c2a52632d32/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Video apiclientcore.js:264:21
Requesting url without automatic networking: http://localhost:8096/Users/7372c70e9ae5440bb3967c2a52632d32/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Audio apiclientcore.js:264:21
Requesting url without automatic networking: http://localhost:8096/Shows/NextUp?Limit=24&Fields=PrimaryImageAspectRatio%2CSeriesInfo%2CDateCreated%2CBasicSyncInfo&UserId=7372c70e9ae5440bb3967c2a52632d32&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CBanner%2CThumb&EnableTotalRecordCount=false apiclientcore.js:264:21
triggering app resume event apphost.js:195:21
app is hidden apphost.js:203:21
triggering app resume event apphost.js:195:21
app is hidden
```

**System (please complete the following information):**
 - OS: Windows
 - Browser: Firefox 70.0b4
 - Jellyfin Version: 10.4.0 (master on server, reports as 10.3.6 web version)

**Comment by sachk** [comment]
This also happens to me, and has happened on every version I have used.

**Comment by EraYaN** [comment]
We could try the `autoStartLoad=false` mode.

**Comment by EraYaN** [comment]
Go away bot!

**Comment by DomiStyle** [comment]
I also noticed this while adding segment deletion and this should be fixed by https://github.com/jellyfin/jellyfin-web/pull/4170 .

**Comment by theevilapplepie** [comment]
@EraYaN - This should have been fixed in [#4170](https://github.com/jellyfin/jellyfin-web/pull/4170), Can you confirm?

**Comment by EraYaN** [comment]
I'll test again tonight so I can look at the actual logs better, it does seem to request -1.mp4 now (looking at the network tab), not sure if that is expected. I'll add some more detail later.
