### ISSUE TITLE
Stuck on logo

### ISSUE THREAD

**Issue by kolbdog3333** [jellyfin/jellyfin-web#5204]
Whenever i open the jellyfin server it is stuck on the logo i can't go to the login screen or anything else.

Here is the log 
[2024-02-13 20:58:44.126 -05:00] [INF] [1] Main: Jellyfin version: "10.8.13"
[2024-02-13 20:58:44.226 -05:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, C:\ProgramData\Jellyfin\Server\log]"]
[2024-02-13 20:58:44.247 -05:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--datadir", "C:\ProgramData\Jellyfin\Server"]
[2024-02-13 20:58:44.269 -05:00] [INF] [1] Main: Operating system: "Windows"
[2024-02-13 20:58:44.277 -05:00] [INF] [1] Main: Architecture: X64
[2024-02-13 20:58:44.287 -05:00] [INF] [1] Main: 64-Bit Process: True
[2024-02-13 20:58:44.291 -05:00] [INF] [1] Main: User Interactive: True
[2024-02-13 20:58:44.297 -05:00] [INF] [1] Main: Processor count: 4
[2024-02-13 20:58:44.304 -05:00] [INF] [1] Main: Program data path: "C:\ProgramData\Jellyfin\Server"
[2024-02-13 20:58:44.309 -05:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2024-02-13 20:58:44.315 -05:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2024-02-13 20:58:45.239 -05:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"CreateNetworkConfiguration"'
[2024-02-13 20:58:45.244 -05:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Migration '"CreateNetworkConfiguration"' applied successfully
[2024-02-13 20:58:45.253 -05:00] [FTL] [1] Main: Unhandled Exception
System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\Jellyfin\Server\config\migrations.xml' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.SerializeToFile(Object obj, String file)
   at Jellyfin.Server.Migrations.MigrationRunner.<>c__DisplayClass3_0.<RunPreStartup>b__1(MigrationOptions options)
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
[2024-02-13 21:00:08.598 -05:00] [INF] [1] Main: Jellyfin version: "10.8.13"
[2024-02-13 21:00:08.640 -05:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, C:\ProgramData\Jellyfin\Server\log]"]
[2024-02-13 21:00:08.652 -05:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--datadir", "C:\ProgramData\Jellyfin\Server"]
[2024-02-13 21:00:08.661 -05:00] [INF] [1] Main: Operating system: "Windows"
[2024-02-13 21:00:08.666 -05:00] [INF] [1] Main: Architecture: X64
[2024-02-13 21:00:08.672 -05:00] [INF] [1] Main: 64-Bit Process: True
[2024-02-13 21:00:08.676 -05:00] [INF] [1] Main: User Interactive: True
[2024-02-13 21:00:08.680 -05:00] [INF] [1] Main: Processor count: 4
[2024-02-13 21:00:08.685 -05:00] [INF] [1] Main: Program data path: "C:\ProgramData\Jellyfin\Server"
[2024-02-13 21:00:08.689 -05:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2024-02-13 21:00:08.693 -05:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2024-02-13 21:00:08.852 -05:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"CreateNetworkConfiguration"'
[2024-02-13 21:00:08.857 -05:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Migration '"CreateNetworkConfiguration"' applied successfully
[2024-02-13 21:00:08.863 -05:00] [FTL] [1] Main: Unhandled Exception
System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\Jellyfin\Server\config\migrations.xml' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.SerializeToFile(Object obj, String file)
   at Jellyfin.Server.Migrations.MigrationRunner.<>c__DisplayClass3_0.<RunPreStartup>b__1(MigrationOptions options)
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
[2024-02-13 21:02:12.739 -05:00] [INF] [1] Main: Jellyfin version: "10.8.13"
[2024-02-13 21:02:12.776 -05:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, C:\ProgramData\Jellyfin\Server\log]"]
[2024-02-13 21:02:12.789 -05:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--datadir", "C:\ProgramData\Jellyfin\Server"]
[2024-02-13 21:02:12.796 -05:00] [INF] [1] Main: Operating system: "Windows"
[2024-02-13 21:02:12.800 -05:00] [INF] [1] Main: Architecture: X64
[2024-02-13 21:02:12.806 -05:00] [INF] [1] Main: 64-Bit Process: True
[2024-02-13 21:02:12.809 -05:00] [INF] [1] Main: User Interactive: True
[2024-02-13 21:02:12.813 -05:00] [INF] [1] Main: Processor count: 4
[2024-02-13 21:02:12.816 -05:00] [INF] [1] Main: Program data path: "C:\ProgramData\Jellyfin\Server"
[2024-02-13 21:02:12.820 -05:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2024-02-13 21:02:12.824 -05:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2024-02-13 21:02:12.982 -05:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"CreateNetworkConfiguration"'
[2024-02-13 21:02:12.988 -05:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Migration '"CreateNetworkConfiguration"' applied successfully
[2024-02-13 21:02:12.996 -05:00] [FTL] [1] Main: Unhandled Exception
System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\Jellyfin\Server\config\migrations.xml' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.SerializeToFile(Object obj, String file)
   at Jellyfin.Server.Migrations.MigrationRunner.<>c__DisplayClass3_0.<RunPreStartup>b__1(MigrationOptions options)
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
[2024-02-13 21:04:04.913 -05:00] [INF] [1] Main: Jellyfin version: "10.8.13"
[2024-02-13 21:04:04.958 -05:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, C:\ProgramData\Jellyfin\Server\log]"]
[2024-02-13 21:04:04.970 -05:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--datadir", "C:\ProgramData\Jellyfin\Server"]
[2024-02-13 21:04:04.979 -05:00] [INF] [1] Main: Operating system: "Windows"
[2024-02-13 21:04:04.983 -05:00] [INF] [1] Main: Architecture: X64
[2024-02-13 21:04:04.989 -05:00] [INF] [1] Main: 64-Bit Process: True
[2024-02-13 21:04:04.993 -05:00] [INF] [1] Main: User Interactive: True
[2024-02-13 21:04:04.997 -05:00] [INF] [1] Main: Processor count: 4
[2024-02-13 21:04:05.000 -05:00] [INF] [1] Main: Program data path: "C:\ProgramData\Jellyfin\Server"
[2024-02-13 21:04:05.004 -05:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2024-02-13 21:04:05.008 -05:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2024-02-13 21:04:05.183 -05:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"CreateNetworkConfiguration"'
[2024-02-13 21:04:05.189 -05:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Migration '"CreateNetworkConfiguration"' applied successfully
[2024-02-13 21:04:05.195 -05:00] [FTL] [1] Main: Unhandled Exception
System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\Jellyfin\Server\config\migrations.xml' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.SerializeToFile(Object obj, String file)
   at Jellyfin.Server.Migrations.MigrationRunner.<>c__DisplayClass3_0.<RunPreStartup>b__1(MigrationOptions options)
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
[2024-02-13 21:04:14.653 -05:00] [INF] [1] Main: Jellyfin version: "10.8.13"
[2024-02-13 21:04:14.692 -05:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, C:\ProgramData\Jellyfin\Server\log]"]
[2024-02-13 21:04:14.703 -05:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--datadir", "C:\ProgramData\Jellyfin\Server"]
[2024-02-13 21:04:14.713 -05:00] [INF] [1] Main: Operating system: "Windows"
[2024-02-13 21:04:14.722 -05:00] [INF] [1] Main: Architecture: X64
[2024-02-13 21:04:14.728 -05:00] [INF] [1] Main: 64-Bit Process: True
[2024-02-13 21:04:14.732 -05:00] [INF] [1] Main: User Interactive: True
[2024-02-13 21:04:14.736 -05:00] [INF] [1] Main: Processor count: 4
[2024-02-13 21:04:14.740 -05:00] [INF] [1] Main: Program data path: "C:\ProgramData\Jellyfin\Server"
[2024-02-13 21:04:14.743 -05:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2024-02-13 21:04:14.746 -05:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2024-02-13 21:04:14.922 -05:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"CreateNetworkConfiguration"'
[2024-02-13 21:04:14.929 -05:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Migration '"CreateNetworkConfiguration"' applied successfully
[2024-02-13 21:04:14.937 -05:00] [FTL] [1] Main: Unhandled Exception
System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\Jellyfin\Server\config\migrations.xml' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.SerializeToFile(Object obj, String file)
   at Jellyfin.Server.Migrations.MigrationRunner.<>c__DisplayClass3_0.<RunPreStartup>b__1(MigrationOptions options)
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
[2024-02-13 21:04:22.327 -05:00] [INF] [1] Main: Jellyfin version: "10.8.13"
[2024-02-13 21:04:22.374 -05:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, C:\ProgramData\Jellyfin\Server\log]"]
[2024-02-13 21:04:22.386 -05:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--datadir", "C:\ProgramData\Jellyfin\Server"]
[2024-02-13 21:04:22.396 -05:00] [INF] [1] Main: Operating system: "Windows"
[2024-02-13 21:04:22.401 -05:00] [INF] [1] Main: Architecture: X64
[2024-02-13 21:04:22.407 -05:00] [INF] [1] Main: 64-Bit Process: True
[2024-02-13 21:04:22.411 -05:00] [INF] [1] Main: User Interactive: True
[2024-02-13 21:04:22.415 -05:00] [INF] [1] Main: Processor count: 4
[2024-02-13 21:04:22.419 -05:00] [INF] [1] Main: Program data path: "C:\ProgramData\Jellyfin\Server"
[2024-02-13 21:04:22.422 -05:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2024-02-13 21:04:22.425 -05:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2024-02-13 21:04:22.596 -05:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"CreateNetworkConfiguration"'
[2024-02-13 21:04:22.600 -05:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Migration '"CreateNetworkConfiguration"' applied successfully
[2024-02-13 21:04:22.606 -05:00] [FTL] [1] Main: Unhandled Exception
System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\Jellyfin\Server\config\migrations.xml' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.SerializeToFile(Object obj, String file)
   at Jellyfin.Server.Migrations.MigrationRunner.<>c__DisplayClass3_0.<RunPreStartup>b__1(MigrationOptions options)
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)
[2024-02-13 21:05:45.287 -05:00] [INF] [1] Main: Jellyfin version: "10.8.13"
[2024-02-13 21:05:45.428 -05:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, C:\ProgramData\Jellyfin\Server\log]"]
[2024-02-13 21:05:45.446 -05:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--datadir", "C:\ProgramData\Jellyfin\Server"]
[2024-02-13 21:05:45.461 -05:00] [INF] [1] Main: Operating system: "Windows"
[2024-02-13 21:05:45.466 -05:00] [INF] [1] Main: Architecture: X64
[2024-02-13 21:05:45.472 -05:00] [INF] [1] Main: 64-Bit Process: True
[2024-02-13 21:05:45.475 -05:00] [INF] [1] Main: User Interactive: True
[2024-02-13 21:05:45.479 -05:00] [INF] [1] Main: Processor count: 4
[2024-02-13 21:05:45.482 -05:00] [INF] [1] Main: Program data path: "C:\ProgramData\Jellyfin\Server"
[2024-02-13 21:05:45.490 -05:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2024-02-13 21:05:45.494 -05:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2024-02-13 21:05:46.598 -05:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Applying migration '"CreateNetworkConfiguration"'
[2024-02-13 21:05:46.647 -05:00] [INF] [1] Jellyfin.Server.Migrations.MigrationRunner: Migration '"CreateNetworkConfiguration"' applied successfully
[2024-02-13 21:05:46.960 -05:00] [FTL] [1] Main: Unhandled Exception
System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\Jellyfin\Server\config\migrations.xml' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.SerializeToFile(Object obj, String file)
   at Jellyfin.Server.Migrations.MigrationRunner.<>c__DisplayClass3_0.<RunPreStartup>b__1(MigrationOptions options)
   at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
   at Jellyfin.Server.Migrations.MigrationRunner.RunPreStartup(ServerApplicationPaths appPaths, ILoggerFactory loggerFactory)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
   at Jellyfin.Server.Program.<Main>(String[] args)

**Comment by thornbill** [comment]
Closing since this is not a place we provide troubleshooting assistance and you didn't bother to use the issue template anyway.

Please see the [getting help](https://jellyfin.org/docs/general/getting-help) page in the docs for appropriate channels to get help. At first glance this looks like a permissions issue though.
