### ISSUE TITLE
Cannot save Notifications setting

### ISSUE THREAD

**Issue by dausruddin** [jellyfin/jellyfin-web#585]
**Describe the bug**
I am trying to enable "New content added" in notifications setting.  When I hit **Save** button, nothing happened but in Dev tools, I can see the the request returned **500 Internal Server Error** with error message `Sequence contains no matching element`. I found out that all settings in Notifications setting cannot be saved.

**To Reproduce**
1. Save Notifications setting

**Expected behavior**
Notifications setting should be saved

**Logs**
```
[2019-11-21 16:48:57.624 +08:00] [ERR] Error processing request
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Emby.Server.Implementations.AppBase.BaseConfigurationManager.GetConfigurationType(String key)
   at MediaBrowser.Api.ConfigurationService.Post(UpdateNamedConfiguration request)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox 70.0.1 (64-bit)
 - Jellyfin Version: 10.4.1

**Comment by dausruddin** [comment]
Perhaps this is related to https://github.com/jellyfin/jellyfin/issues/1881 ?
But I don't have problem saving another settings. Just only for Notifications setting.

**Comment by dausruddin** [comment]
I think it is. So I'm just gonna close this. Thanks.
