### ISSUE TITLE
Unable to delete Access Schedules from Parental Control menu

### ISSUE THREAD

**Issue by Skin80** [jellyfin/jellyfin-web#6119]
**Describe The Bug**
Under Parental Control, there is the ability to add or remove Access Schedule. Currently you can add a new schedule item, but pressing the delete (trash can) icon does nothing. Trying to refresh the page after clicking the delete icon results in a JS error.

**Steps To Reproduce**

1. Click on Dashboard
2. Go to Users
3. Select a User
4. Go to Parental Control
5. Try to delete an Access Schedule

**Expected Behavior**
Removed schedule should no longer appear and access rescinded.

**Logs**
TypeError

a is null

le@http://192.168.1.10:8096/web/73233.294285d0ae14263ac91a.chunk.js:2:12493
73233@http://192.168.1.10:8096/web/73233.294285d0ae14263ac91a.chunk.js:2:17829
s@http://192.168.1.10:8096/web/runtime.bundle.js?cb9605c13a12ef3dce91:1:155
78304@http://192.168.1.10:8096/web/users-parentalcontrol.bf742afb5e8cedfcb442.chunk.js:1:2807
s@http://192.168.1.10:8096/web/runtime.bundle.js?cb9605c13a12ef3dce91:1:155
38601/i/<@http://192.168.1.10:8096/web/main.jellyfin.bundle.js?cb9605c13a12ef3dce91:2:446851

**Screenshots**

**System (please complete the following information):**
 - Linux, Windows, iPhone, Tizen (tried on all of them)
 -  Firefox, Chrome, Edge
 - Jellyfin Version: 10.10.0

**Additional Context**

**Comment by Skin80** [comment]
Error above is from Firefox. Get a slightly different one in Edge and Chrome:

TypeError
Cannot read properties of null (reading 'querySelector')

TypeError: Cannot read properties of null (reading 'querySelector')
    at le (http://192.168.1.10:8096/web/73233.294285d0ae14263ac91a.chunk.js:2:12497)
    at 73233 (http://192.168.1.10:8096/web/73233.294285d0ae14263ac91a.chunk.js:2:17829)
    at s (http://192.168.1.10:8096/web/runtime.bundle.js?cb9605c13a12ef3dce91:1:155)
    at 78304 (http://192.168.1.10:8096/web/users-parentalcontrol.bf742afb5e8cedfcb442.chunk.js:1:2806)
    at s (http://192.168.1.10:8096/web/runtime.bundle.js?cb9605c13a12ef3dce91:1:155)
    at http://192.168.1.10:8096/web/main.jellyfin.bundle.js?cb9605c13a12ef3dce91:2:446851

**Comment by viown** [comment]
If you create a new schedule, exit and then re-open the page, are you able to delete it?

**Comment by Skin80** [comment]
No, same issue, even with newly created schedules. Clicking the delete button doesn't appear to do anything, but then the errors above popup if I try refreshing the page. So, must be doing something, just not the right thing 😊

**Comment by viown** [comment]
It looks like you're also mentioning a separate issue where refreshing the profile page will result in the page not loading with an error.

**Comment by Skin80** [comment]
Sorry, yes, you're right. I didn't realise the JS error occurred regardless of anything done on the Parental Control page. I (erroneously) thought they only occurred after trying to delete a schedule.

Would you like me to raise a separate ticket for the JS error?

**Comment by viown** [comment]
Sure.
