### ISSUE TITLE
Browsing to "dashboard/users/access" or "dashboard/devices" causes mdl-spinner and "Error processing request. URL GET /Devices."

### ISSUE THREAD

**Issue by mjevange** [jellyfin/jellyfin-web#6147]
**Describe The Bug**

When browsing to modify any user's library access or Devices, the pages will not load and only see middle spinner perpetually.
Checking logs, we see:
`[ERR] [32] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL GET /Devices.
System.ArgumentException: The value cannot be an empty string. (Parameter 'deviceId')`

**Steps To Reproduce**

1. Go to "Dashboard > Users > Any user > Access" **OR** "Dashboard > Devices"
2. Pages will not finish loading
3. Only see middle spinner

**Expected Behavior**

-Library access should show available libraries as options, if All libraries is not checked.
-Devices should display
-Pages should load and be functional
-Middle spinner would disappear upon page load

**Logs**

[ERR] [32] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL GET /Devices.
System.ArgumentException: The value cannot be an empty string. (Parameter 'deviceId')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at Jellyfin.Server.Implementations.Devices.DeviceManager.CanAccessDevice(User user, String deviceId)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at Jellyfin.Server.Implementations.Devices.DeviceManager.GetDevicesForUser(Nullable`1 userId)
   at lambda_method1114(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)

**Screenshots**

![image](https://github.com/user-attachments/assets/b95d00fb-0d51-455e-9f0f-dd028b438d22)
![image](https://github.com/user-attachments/assets/44303cdf-29fc-4913-be88-ccbc88caf97e)

**System (please complete the following information):**
 - Platform: Linux Container
 - Browser: Firefox, Chrome, Edge
 - Jellyfin Version: 10.9.11 (also tested rolling back to 10.9.10, 10.9.9, and 10.9.4)

**Additional Context**

I also tested the "Delete All" button in the Devices page. It did not seem to do anything, nor did it produce any logs.

**Comment by mjevange** [comment]
Is this in the right place? or should it go **jellyfin/jellyfin/issues**

**Comment by viown** [comment]
Are you able to create a new user? If so, can you try creating a new user and setting it an admin and see if you can access those pages.

**Comment by viown** [comment]
Upon closer inspection, you might have a device with an empty DeviceId in your database (https://github.com/jellyfin/jellyfin/blob/9604088e3cfd1828a5f621341035adbf1b5e73e7/Jellyfin.Server.Implementations/Devices/DeviceManager.cs#L236)

Here's what I would do:

1. Create a copy of the `jellyfin.db` file (located in JF's data path)
2. Open the file using something like DB Browser (https://sqlitebrowser.org/)
3. Analyze your `Devices` table, try to find an entry which could be causing the issue.

Modifying the database directly is not a recommended procedure, but if you are going to do so, make sure to create a full backup of all your JF directories beforehand.

**Comment by mjevange** [comment]
I was able to locate and remove the record with missing DeviceID in the Devices table which resolved the issue.
Thank you @viown

**Comment by viown** [comment]
It's a long shot, but if you can figure out how that device got created, it may be worth opening an issue at https://github.com/jellyfin/jellyfin

**Comment by mjevange** [comment]
It was caused by this client: https://github.com/dragonflylee/switchfin
Issue might be better suited there so they properly report their ID

**Comment by viown** [comment]
The server shouldn't allow devices with empty Ids, so it's better to get this fixed at the source.
