### ISSUE TITLE
Blank images

### ISSUE THREAD

**Issue by dannymichel** [jellyfin/jellyfin-web#790]
I'm out of it right now, so a video is gonna have to do.
Sometimes images are blank
https://gph.is/g/Z5YJz9k
https://www.dropbox.com/s/7sbrh8ic5jl6knw/blank.mp4

**Comment by Artiume** [comment]
Looks like a cache issue. The web ui refactoring should take care of it.

**Comment by MrTimscampi** [comment]
@dannymichel Could you try opening the Developer Tools (F12) in a browser where this happens, then go to the Network tab and check "Disable cache". Then try reloading the page and see if the image pops up.

If it does, it's a cache issue. If not, it may be something else.

**Comment by Artiume** [comment]
Shoo bot

**Comment by MrTimscampi** [comment]
> Shoo bot

If we don't have more info, it's hard to fix it :p

I haven't seen this on my end and I don't know of any other reports about this. With the recent rework of the image loader, I think it's okay to let this go stale or even close it.

**Comment by Artiume** [comment]
So I personally experience this still. I haven't pulled justaman's cache fix nor the new loader. I'm hoping this gets closed out soon enough :) 

![Screenshot_20200511-073719_Jellyfin](https://user-images.githubusercontent.com/20715731/81557798-91c26f80-935a-11ea-8177-5ea0544f9406.jpg)

**Comment by MrTimscampi** [comment]
If you can test with master for both the server and the web client, it'd be nice :)

**Comment by PrplHaz4** [comment]
I'm seeing a similar issue for my LiveTV "library" (on today's master).  It is coupled with a bunch of 500 errors in the web console with matching exceptions on the backend.  The lack of info in this issue report makes it tough for me to tell if it's the same - so I can open a new one if it's not.

One thing I notice about my issue is that the web client requests a HTTPS url but HTTP is logged.  I am behind a reverse proxy with security mode "Disabled".

Firefox Console (looks like some images are cached and not failing, but most look like this):
```
Request URL:https://jftest2.example.com/Items/b0f9511ac96817add4624f42276f4d78/Images/Primary?maxWidth=711&tag=61d5cba733bca97dd647fa08b8678dd0&quality=90
Request Method:GET
Remote Address:192.168.1.xxx:443
Status Code: 500 Internal Server Error
Response Payload: "Forbidden"
```
Server Log:
```
[13:14:15] [ERR] Error processing request. URL: http://jftest2.example.com/Items/b0f9511ac96817add4624f42276f4d78/Images/Primary?maxWidth=711&tag=61d5cba733bca97dd647fa08b8678dd0&quality=90
MediaBrowser.Model.Net.HttpException: Forbidden
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.EnsureSuccessStatusCode(HttpResponseMessage response, HttpRequestOptions options) in /opt/jellyfin/Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs:line 329
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsyncInternal(HttpRequestOptions options, HttpMethod httpMethod) in /opt/jellyfin/Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs:line 266
   at Emby.Server.Implementations.HttpClientManager.HttpClientManager.SendAsync(HttpRequestOptions options, HttpMethod httpMethod) in /opt/jellyfin/Emby.Server.Implementations/HttpClientManager/HttpClientManager.cs:line 172
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken) in /opt/jellyfin/MediaBrowser.Providers/Manager/ProviderManager.cs:line 146
   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex) in /opt/jellyfin/Emby.Server.Implementations/Library/LibraryManager.cs:line 2791
   at MediaBrowser.Api.Images.ImageService.GetImageResult(BaseItem item, Guid itemId, ImageRequest request, ItemImageInfo image, Boolean cropwhitespace, IReadOnlyCollection`1 supportedFormats, Nullable`1 cacheDuration, IDictionary`2 headers, Boolean isHeadRequest) in /opt/jellyfin/MediaBrowser.Api/Images/ImageService.cs:line 613
   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /opt/jellyfin/Emby.Server.Implementations/Services/ServiceExec.cs:line 108
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken) in /opt/jellyfin/Emby.Server.Implementations/Services/ServiceHandler.cs:line 80
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /opt/jellyfin/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 531

[13:14:15] [DBG] Sending HTTP Response 500 in response to http://jftest2.example.com/Items/b0f9511ac96817add4624f42276f4d78/Images/Primary?maxWidth=711&tag=61d5cba733bca97dd647fa08b8678dd0&quality=90
```

**Comment by ferferga** [comment]
I can confirm that this seems like a server issue, because going to the image URL returns a 403 Forbidden error after a long time trying to load. However, the server returns that an image exists, that's why the placeholder is not used instead.

@jellyfin/triage Can you move this, please?
