### ISSUE TITLE
Could not build in Docker

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [jellyfin/jellyfin-web#945]
Logs [here](https://gist.github.com/ThatNerdyPikachu/15daeff05d99088a0a89f7cdacbc9d76).

Latest master Dockerfile from server repo.

**Comment by MrTimscampi** [comment]
Due to the recent addition of Gulp to the build process, the Docker image needs a few more dependencies.

See here: https://github.com/jellyfin/jellyfin-web/pull/862#issuecomment-593440878

We'll adjust the images shortly. Thanks :)

**Comment by Artiume** [comment]
issues updated arm version

```
OK: 173 MiB in 76 packages
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   129  100   129    0     0    544      0 --:--:-- --:--:-- --:--:--   544
100 3591k    0 3591k    0     0  4026k      0 --:--:-- --:--:-- --:--:-- 4026k
yarn install v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check.                                                                                                     Excluding it from installation.
[3/4] Linking dependencies...
```
Everything appears normal until here.
```
[4/4] Building fresh packages...
error /jellyfin-web-master/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: /jellyfin-web-master/node_modules/node-sass
Output:
Building: /usr/local/bin/node /jellyfin-web-master/node_modules/node-gyp/bin/nod                                                                                                    e-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= -                                                                                                    -libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/bin/node',
gyp verb cli   '/jellyfin-web-master/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@13.1.0 | linux | arm
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/jellyfin-web-master/node_modul                                                                                                    es/which/which.js:13:12)
gyp verb `which` failed     at F (/jellyfin-web-master/node_modules/which/which.                                                                                                    js:68:19)
gyp verb `which` failed     at E (/jellyfin-web-master/node_modules/which/which.                                                                                                    js:80:29)
gyp verb `which` failed     at /jellyfin-web-master/node_modules/which/which.js:                                                                                                    89:16
gyp verb `which` failed     at /jellyfin-web-master/node_modules/isexe/index.js:                                                                                                    42:5
gyp verb `which` failed     at /jellyfin-web-master/node_modules/isexe/mode.js:8                                                                                                    :5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/jellyfin-web-master/node_modul                                                                                                    es/which/which.js:13:12)
gyp verb `which` failed     at F (/jellyfin-web-master/node_modules/which/which.                                                                                                    js:68:19)
gyp verb `which` failed     at E (/jellyfin-web-master/node_modules/which/which.                                                                                                    js:80:29)
gyp verb `which` failed     at /jellyfin-web-master/node_modules/which/which.js:                                                                                                    89:16
gyp verb `which` failed     at /jellyfin-web-master/node_modules/isexe/index.js:                                                                                                    42:5
gyp verb `which` failed     at /jellyfin-web-master/node_modules/isexe/mode.js:8                                                                                                    :5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n' +
gyp verb `which` failed     '    at getNotFoundError (/jellyfin-web-master/node_                                                                                                    modules/which/which.js:13:12)\n' +
gyp verb `which` failed     '    at F (/jellyfin-web-master/node_modules/which/w                                                                                                    hich.js:68:19)\n' +
gyp verb `which` failed     '    at E (/jellyfin-web-master/node_modules/which/w                                                                                                    hich.js:80:29)\n' +
gyp verb `which` failed     '    at /jellyfin-web-master/node_modules/which/whic                                                                                                    h.js:89:16\n' +
gyp verb `which` failed     '    at /jellyfin-web-master/node_modules/isexe/inde                                                                                                    x.js:42:5\n' +
gyp verb `which` failed     '    at /jellyfin-web-master/node_modules/isexe/mode                                                                                                    .js:8:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/jellyfin-web-master/node_modul                                                                                                    es/which/which.js:13:12)
gyp verb `which` failed     at F (/jellyfin-web-master/node_modules/which/which.                                                                                                    js:68:19)
gyp verb `which` failed     at E (/jellyfin-web-master/node_modules/which/which.                                                                                                    js:80:29)
gyp verb `which` failed     at /jellyfin-web-master/node_modules/which/which.js:                                                                                                    89:16
gyp verb `which` failed     at /jellyfin-web-master/node_modules/isexe/index.js:                                                                                                    42:5
gyp verb `which` failed     at /jellyfin-web-master/node_modules/isexe/mode.js:8                                                                                                    :5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (/jellyfin-web-master/node_modul                                                                                                    es/which/which.js:13:12)
gyp verb `which` failed     at F (/jellyfin-web-master/node_modules/which/which.                                                                                                    js:68:19)
gyp verb `which` failed     at E (/jellyfin-web-master/node_modules/which/which.                                                                                                    js:80:29)
gyp verb `which` failed     at /jellyfin-web-master/node_modules/which/which.js:                                                                                                    89:16
gyp verb `which` failed     at /jellyfin-web-master/node_modules/isexe/index.js:                                                                                                    42:5
gyp verb `which` failed     at /jellyfin-web-master/node_modules/isexe/mode.js:8                                                                                                    :5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21) {
gyp verb `which` failed   stack: 'Error: not found: python\n' +
gyp verb `which` failed     '    at getNotFoundError (/jellyfin-web-master/node_                                                                                                    modules/which/which.js:13:12)\n' +
gyp verb `which` failed     '    at F (/jellyfin-web-master/node_modules/which/w                                                                                                    hich.js:68:19)\n' +
gyp verb `which` failed     '    at E (/jellyfin-web-master/node_modules/which/w                                                                                                    hich.js:80:29)\n' +
gyp verb `which` failed     '    at /jellyfin-web-master/node_modules/which/whic                                                                                                    h.js:89:16\n' +
gyp verb `which` failed     '    at /jellyfin-web-master/node_modules/isexe/inde                                                                                                    x.js:42:5\n' +
gyp verb `which` failed     '    at /jellyfin-web-master/node_modules/isexe/mode                                                                                                    .js:8:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:158:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT                                                                                                    HON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/jellyfin-web-master/node_modul                                                                                                    es/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/jellyfin-web-master/node_module                                                                                                    s/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/jellyfin-web-master/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/jellyfin-web-master/node_modules/which/which.js:80:29)
gyp ERR! stack     at /jellyfin-web-master/node_modules/which/which.js:89:16
gyp ERR! stack     at /jellyfin-web-master/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /jellyfin-web-master/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
gyp ERR! System Linux 4.19.97-v7l+
gyp ERR! command "/usr/local/bin/node" "/jellyfin-web-master/node_modules/node-g                                                                                                    yp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "                                                                                                    --libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /jellyfin-web-master/node_modules/node-sass
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this                                                                                                     command.
The command '/bin/sh -c apk add curl git zlib zlib-dev autoconf g++ make libpng-                                                                                                    dev gifsicle alpine-sdk automake libtool make gcc musl-dev nasm  && curl -L http                                                                                                    s://github.com/jellyfin/jellyfin-web/archive/${JELLYFIN_WEB_VERSION}.tar.gz | ta                                                                                                    r zxf -  && cd jellyfin-web-*  && yarn install  && yarn build  && mv dist /dist'                                                                                                     returned a non-zero code: 1
```
